/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { IQueryClientProvider, ISigningClientProvider, IMessageComposerProvider } from "./contractContextBase";
import { DappTemplateQueryClient } from "./DappTemplate.client";
import { DappTemplateClient } from "./DappTemplate.client";
import { DappTemplateMsgComposer } from "./DappTemplate.message-composer";
import { DappTemplate } from "./DappTemplate.provider";
export interface IContractsContext {
  dappTemplate: IQueryClientProvider<DappTemplateQueryClient> & ISigningClientProvider<DappTemplateClient> & IMessageComposerProvider<DappTemplateMsgComposer>;
}
export const getProviders = (address?: string, cosmWasmClient?: CosmWasmClient, signingCosmWasmClient?: SigningCosmWasmClient) => ({
  dappTemplate: new DappTemplate({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  })
});