/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { DappTemplateClient, DappTemplateQueryClient } from "./DappTemplate.client";
import { DappTemplateMsgComposer } from "./DappTemplate.message-composer";
export class DappTemplate extends ContractBase<DappTemplateClient, DappTemplateQueryClient, DappTemplateMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, DappTemplateClient, DappTemplateQueryClient, DappTemplateMsgComposer);
  }
}