/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { InstantiateMsg, ExecuteMsg, Action, Expiration, Timestamp, Uint64, QueryMsg, MigrateMsg, CountResponse, OwnershipForString } from "./DappTemplate.types";
import { CamelCasedProperties } from "type-fest";
export abstract class DappTemplateExecuteMsgBuilder {
  static increment = (): ExecuteMsg => {
    return {
      increment: ({} as const)
    };
  };
  static reset = ({
    count
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    reset: unknown;
  }>["reset"]>): ExecuteMsg => {
    return {
      reset: ({
        count
      } as const)
    };
  };
  static updateOwnership = (action: Action): ExecuteMsg => {
    return {
      update_ownership: action
    };
  };
}
export abstract class DappTemplateQueryMsgBuilder {
  static getCount = (): QueryMsg => {
    return {
      get_count: ({} as const)
    };
  };
  static ownership = (): QueryMsg => {
    return {
      ownership: ({} as const)
    };
  };
}