/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./DappTemplate.types";
import * as _1 from "./DappTemplate.client";
import * as _2 from "./DappTemplate.message-composer";
import * as _3 from "./DappTemplate.message-builder";
import * as _4 from "./DappTemplate.provider";
import * as _5 from "./contractContextProviders";
import * as _6 from "./contractContextBase";
import * as _7 from "./contracts-context";
export namespace contracts {
  export const DappTemplate = {
    ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
  export const undefined = {
    ..._5
  };
  export const contractContextBase = {
    ..._6
  };
  export const contractsContext = {
    ..._7
  };
}